AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Network Template (ipv6 enable)
Parameters:
  VPCCIDR:
    Description: First and Second Octet of VPC, For example xxx.xxx
    Type: String
    Default: '192.168'
    ConstraintDescription: xxx.xxx
  NameTagPrefix:
    Type: String
    Default: v6test
    Description: Prefix of Name tags.
Mappings:
  StackConfig:
    VPC:
      CIDR: .0.0/20
    FrontendSubnet1:
      CIDR: .0.0/24
    FrontendSubnet2:
      CIDR: .1.0/24
    ApplicationSubnet1:
      CIDR: .2.0/24
    ApplicationSubnet2:
      CIDR: .3.0/24
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Sub ['${VPCCIDR}${Param1}', {Param1: !FindInMap [StackConfig, VPC,
            CIDR]}]
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Sub '${NameTagPrefix}-VPC'
  #ipv4 config
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Sub '${NameTagPrefix}-IGW'
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref 'VPC'
      InternetGatewayId: !Ref 'InternetGateway'
  FrontendRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGateway
    Properties:
      VpcId: !Ref 'VPC'
      Tags:
      - Key: Name
        Value: !Sub '${NameTagPrefix}-FrontendRoute'
  FrontendRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref 'FrontendRouteTable'
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref 'InternetGateway'
  ApplicationRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGateway
    Properties:
      VpcId: !Ref 'VPC'
      Tags:
      - Key: Name
        Value: !Sub '${NameTagPrefix}-ApplicationRoute'
  ApplicationRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref 'ApplicationRouteTable'
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref 'InternetGateway'
  FrontendSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      AvailabilityZone: !Select [0, !GetAZs {Ref: 'AWS::Region'}]
      CidrBlock: !Sub ['${VPCCIDR}${Param1}', {Param1: !FindInMap [StackConfig, FrontendSubnet1,
            CIDR]}]
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub '${NameTagPrefix}-FrontendSubnet1'
      VpcId: !Ref 'VPC'
  FrontendSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref 'FrontendSubnet1'
      RouteTableId: !Ref 'FrontendRouteTable'
  FrontendSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      AvailabilityZone: !Select [1, !GetAZs {Ref: 'AWS::Region'}]
      CidrBlock: !Sub ['${VPCCIDR}${Param1}', {Param1: !FindInMap [StackConfig, FrontendSubnet2,
            CIDR]}]
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub '${NameTagPrefix}-FrontendSubnet2'
      VpcId: !Ref 'VPC'
  FrontendSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref 'FrontendSubnet2'
      RouteTableId: !Ref 'FrontendRouteTable'
  ApplicationSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      AvailabilityZone: !Select [0, !GetAZs {Ref: 'AWS::Region'}]
      CidrBlock: !Sub ['${VPCCIDR}${Param1}', {Param1: !FindInMap [StackConfig, ApplicationSubnet1,
            CIDR]}]
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub '${NameTagPrefix}-ApplicationSubnet1'
      VpcId: !Ref 'VPC'
  ApplicationSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref 'ApplicationSubnet1'
      RouteTableId: !Ref 'ApplicationRouteTable'
  ApplicationSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      AvailabilityZone: !Select [1, !GetAZs {Ref: 'AWS::Region'}]
      CidrBlock: !Sub ['${VPCCIDR}${Param1}', {Param1: !FindInMap [StackConfig, ApplicationSubnet2,
            CIDR]}]
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub '${NameTagPrefix}-ApplicationSubnet2'
      VpcId: !Ref 'VPC'
  ApplicationSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref 'ApplicationSubnet2'
      RouteTableId: !Ref 'ApplicationRouteTable'

  #ipv6 config
  Ipv6VPCCidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      AmazonProvidedIpv6CidrBlock: true
      VpcId: !Ref 'VPC'
  EgressOnlyInternetGateway:
    Type: AWS::EC2::EgressOnlyInternetGateway
    Properties:
      VpcId: !Ref 'VPC'
  FrontendRouteV6:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref 'FrontendRouteTable'
      DestinationIpv6CidrBlock: ::/0
      GatewayId: !Ref 'InternetGateway'
  ApplicationRouteV6:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref 'ApplicationRouteTable'
      DestinationIpv6CidrBlock: ::/0
      EgressOnlyInternetGatewayId: !Ref 'EgressOnlyInternetGateway'
  FrontendSubnet1CidrBlock:
    Type: AWS::EC2::SubnetCidrBlock
    Properties:
      Ipv6CidrBlock: !Sub ['${Param1}00::/64', {Param1: !Select ['0', !Split ['00::/',
              !Select [0, !GetAtt 'VPC.Ipv6CidrBlocks']]]}]
      SubnetId: !Ref 'FrontendSubnet1'
  FrontendSubnet2CidrBlock:
    Type: AWS::EC2::SubnetCidrBlock
    Properties:
      Ipv6CidrBlock: !Sub ['${Param1}01::/64', {Param1: !Select ['0', !Split ['00::/',
              !Select [0, !GetAtt 'VPC.Ipv6CidrBlocks']]]}]
      SubnetId: !Ref 'FrontendSubnet2'
  ApplicationSubnet1CidrBlock:
    Type: AWS::EC2::SubnetCidrBlock
    Properties:
      Ipv6CidrBlock: !Sub ['${Param1}02::/64', {Param1: !Select ['0', !Split ['00::/',
              !Select [0, !GetAtt 'VPC.Ipv6CidrBlocks']]]}]
      SubnetId: !Ref 'ApplicationSubnet1'
  ApplicationSubnet2CidrBlock:
    Type: AWS::EC2::SubnetCidrBlock
    Properties:
      Ipv6CidrBlock: !Sub ['${Param1}03::/64', {Param1: !Select ['0', !Split ['00::/',
              !Select [0, !GetAtt 'VPC.Ipv6CidrBlocks']]]}]
      SubnetId: !Ref 'ApplicationSubnet2'

Outputs:
  VPC:
    Value: !Ref 'VPC'
  Ipv4CidrBlock:
    Value: !GetAtt VPC.CidrBlock
  FrontendSubnet1:
    Value: !Ref 'FrontendSubnet1'
  FrontendSubnet2:
    Value: !Ref 'FrontendSubnet2'
  FrontendSubnet1Ipv4Cidr:
    Value: !Sub ['${VPCCIDR}${Param1}', {Param1: !FindInMap [StackConfig, FrontendSubnet1,CIDR]}]
  FrontendSubnet2Ipv4Cidr:
    Value: !Sub ['${VPCCIDR}${Param1}', {Param1: !FindInMap [StackConfig, FrontendSubnet2,CIDR]}]
  ApplicationSubnet1:
    Value: !Ref 'FrontendSubnet1'
  ApplicationSubnet2:
    Value: !Ref 'FrontendSubnet2'
  ApplicationSubnet1Ipv4Cidr:
    Value: !Sub ['${VPCCIDR}${Param1}', {Param1: !FindInMap [StackConfig, FrontendSubnet1,CIDR]}]
  ApplicationSubnet2Ipv4Cidr:
    Value: !Sub ['${VPCCIDR}${Param1}', {Param1: !FindInMap [StackConfig, FrontendSubnet2,CIDR]}]
  Ipv6CidrBlock:
    Value: !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]
  FrontendSubnet1Ipv6CidrBlocks:
    Value: !Select [ 0, !GetAtt FrontendSubnet1.Ipv6CidrBlocks ]
  FrontendSubnet2Ipv6CidrBlocks:
    Value: !Select [ 0, !GetAtt FrontendSubnet2.Ipv6CidrBlocks ]
  ApplicationSubnet1Ipv6CidrBlocks:
    Value: !Select [ 0, !GetAtt ApplicationSubnet1.Ipv6CidrBlocks ]
  ApplicationSubnet2Ipv6CidrBlocks:
    Value: !Select [ 0, !GetAtt ApplicationSubnet2.Ipv6CidrBlocks ]
  FrontendRouteTable: 
    Value: !Ref 'FrontendRouteTable'
  ApplicationRouteTable: 
    Value: !Ref 'ApplicationRouteTable'